### ISSUE TITLE
Please rebase/re-sync this fork with mine

### ISSUE THREAD

**Issue by VanessaE** [HybridDog/titanium#1]
It seems as if you're the one maintaining this mod, so I would appreciate it if you could re-sync/rebase yours against mine, or vice-versa.  I'd rather not continue to maintain my fork if it's outdated :stuck_out_tongue: 

Mine has more of the original code's history, some of which came from yours.  https://gitlab.com/VanessaE/titanium

**Comment by HybridDog** [comment]
I've rebased it to your repository now and changed commit messages.

**Comment by VanessaE** [comment]
:+1:
